### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by GMartigny** [flexdinesh/dev-landing-page#1]
Hi,

I love the ease of use this repo. It could, however, go a little further and guide user to [use custom domain](https://help.github.com/articles/quick-start-setting-up-a-custom-domain/).

It just need a `CNAME` file with the URL and a bit of configuration repo's settings.

However, the domain register + DNS provider part is a bit trickier. I don't know if it fits this repo's mindset.

**Comment by flexdinesh** [comment]
@GMartigny That sounds like a wonderful idea. It's always good to add more related info just in case people need direction. I'm going to add `help wanted` label to this issue. I'll try to see through this in the next week or if you have enough bandwidth in the meanwhile feel free to create a PR with the instructions.
