### ISSUE TITLE
Flag as template repo

### ISSUE THREAD

**Issue by michaelsanford** [flexdinesh/dev-landing-page#11]
Github allows creating so-called [template repositories](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository), which this one arguably is. Check "Template" under the repo name in settings.

That said, this is awesome @flexdinesh ! Thanks for making it. 👏  👏

**Comment by flexdinesh** [comment]
Awesome, didn't know that. Just marked this repo as a template repo. Although quite not sure if this technically qualifies as one but can always work it out later. Thanks again! @michaelsanford
